### PR TITLE
DOCS: create getting started section

### PR DESCRIPTION
**Pull request by Robbe-Haegeman**
The current best way to get started with the project is to either run or read the provided full_test shell files.
This makes it hard for a developer to understand what is going on within the project.
I've started from those shell files (mostly run_wasm.sh) and parsed the steps in an information dump.
I then used this information dump to create docs.

My current proposal has some flaws:
- I've not had the time to test the comb-rust-controller and ring-rust-controller examples
- The testing and profiling sections are very barebones, due to the problem above.
- It is sometimes easier to let a script generate the yaml manifests than it is to modify them yourself  
  I however believe that having the ability to easily start from and modify the yaml's outweigh this negative

This proposal includes:
- A setup section going through the setup of Kind, the prediction server and the building tools
- A usage section going over the setup of the child operators
- A very WIP testing section, which I would like to move to the individual operators (but due to lack of testing the others + how similar they all are hasn't been done)
- A profiling section which just contains the proper python command
- The YAML files, which are normally "dynamically" generated by the shell script (in quotes since some generate the same file each time)

### CODE REVIEW

**Review by merlijn-sebrechts — APPROVED** [review]
Looks good! At some point, it might be useful to use markdownlint too. I see a lot of code smells in your markdown, like how you use whitespace.

I'll leave it up to you if you want to fix this now or later, though. This is already such an improvement that I'm happy to merge it as-is.

**Comment by Robbe-Haegeman** [comment]
I've now added markdownlint to the contributing section and ran it against all of the markdown files in the repo.
I kept the settings as close to default as possible apart from 2 changes:

- Allow HTML to be able to use \<br\> tags in markdown tables
- Disable line-length in code blocks, since these often don't allow separation over mutliple lines

**Comment by merlijn-sebrechts** [comment]
Oh, I apologize for not saying this earlier, but can you ignore line length everywhere in markdown documents? It really makes it difficult to parse commits and merge requests if the entire document changes just because the length of one line changed, pushing up everything else.

**Comment by Robbe-Haegeman** [comment]
Sure! I'll create a commit to revert the previous one first and then re-add the changes in a separate commit.
Shouldn't take long :)

EDIT: this has now been done!

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
